[project]
name = "async-pokemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.13",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "requests>=2.32.3",
    "uvloop>=0.21.0",
]
